baseURL = "https://simka.dev"
languageCode = "en-us"
title = "simka"
disableKinds = ["taxonomy", "term"]

[params]
description = "personal site of maciej simka, software developer"

  [[params.social]]
  name = "github"
  label = "github"
  url = "https://github.com/simka"

  [[params.social]]
  name = "stack overflow"
  label = "stack overflow"
  url = "https://stackoverflow.com/users/6126368/simka"

  [[params.social]]
  name = "linkedin"
  label = "linkedin"
  url = "https://www.linkedin.com/in/maciejsimka/"

  [[params.social]]
  name = "goodreads"
  label = "books i read"
  url = "https://www.goodreads.com/simka"

  [[params.social]]
  name = "letterboxd"
  label = "movies i watch"
  url = "https://letterboxd.com/mcjsimka/"

  [[params.social]]
  name = "soundcloud"
  label = "sounds i make"
  url = "https://soundcloud.com/decorative-houseplant"

[build]
# Used to PurgeCSS
writeStats = true

